# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ce9adbb1d9ab001110a487af8031e9fe3517f443dd30e7fe21d6905afbe043eb23dfa41ff80364379ba2b854bff7b81c09b269ca3f8d21240d22b4a6065566f

test:
  secret_key_base: f42365c083a275af8350326a4bf6d3f90476275f00fd1301fbb37dade527c66e76e18e4db4265d56daf5d21123dc0a7cd71a73062d21192dc10f7bedd2983256

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
